<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-ReviewsWebApplication-21B70C0C-302C-4A0A-89A4-95EEABEF2BC4</UserSecretsId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Data\**" />
	  <Compile Remove="Services\**" />
	  <Content Remove="Data\**" />
	  <Content Remove="Services\**" />
	  <EmbeddedResource Remove="Data\**" />
	  <EmbeddedResource Remove="Services\**" />
	  <None Remove="Data\**" />
	  <None Remove="Services\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.25" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.25" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.25" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.25">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.25" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.25">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Identity.Web" Version="1.16.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="StackExchange.Redis" Version="2.6.122" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Review.Domain\Review.Domain.csproj" />
	</ItemGroup>
</Project>
