// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Domain;

#nullable disable

namespace Review.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20251202175124_AddRatingAndReviewCountToReview")]
    partial class AddRatingAndReviewCountToReview
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Review.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 10, 13, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7129),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 9, 18, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7175),
                            Grade = 3,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 12, 1, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7182),
                            Grade = 1,
                            ProductId = 7,
                            Rating = 2.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 8, 27, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7186),
                            Grade = 1,
                            ProductId = 7,
                            Rating = 2.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 11, 24, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7191),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 10, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7199),
                            Grade = 4,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 9, 11, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7204),
                            Grade = 1,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 11, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7208),
                            Grade = 2,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 9
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 11, 22, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7212),
                            Grade = 3,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2025, 9, 4, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7219),
                            Grade = 5,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2025, 9, 17, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7224),
                            Grade = 1,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 9
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2025, 11, 28, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7229),
                            Grade = 4,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2025, 11, 10, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7232),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2025, 11, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7237),
                            Grade = 5,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2025, 9, 18, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7241),
                            Grade = 5,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2025, 11, 25, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7245),
                            Grade = 4,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2025, 9, 28, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7250),
                            Grade = 2,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit ame",
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2025, 10, 21, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7257),
                            Grade = 5,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 6
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2025, 9, 7, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7262),
                            Grade = 5,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 6
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2025, 10, 16, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7266),
                            Grade = 4,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = 4
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2025, 11, 22, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7270),
                            Grade = 5,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2025, 9, 6, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7275),
                            Grade = 2,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2025, 9, 19, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7279),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 9
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2025, 9, 7, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7283),
                            Grade = 4,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid",
                            UserId = 9
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2025, 10, 6, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7365),
                            Grade = 3,
                            ProductId = 7,
                            Rating = 2.1699999999999999,
                            ReviewCount = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 4
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2025, 9, 25, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7371),
                            Grade = 3,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2025, 10, 15, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7375),
                            Grade = 5,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = 5
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2025, 11, 2, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7378),
                            Grade = 5,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2025, 11, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7384),
                            Grade = 1,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2025, 9, 18, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7389),
                            Grade = 4,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = 3
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2025, 10, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7394),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = 6
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2025, 11, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7398),
                            Grade = 5,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2025, 9, 1, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7402),
                            Grade = 5,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = 7
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2025, 11, 13, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7410),
                            Grade = 5,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = 7
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2025, 9, 10, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7413),
                            Grade = 4,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = 9
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2025, 8, 24, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7417),
                            Grade = 1,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2025, 10, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7421),
                            Grade = 5,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2025, 8, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7425),
                            Grade = 4,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 3
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2025, 8, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7429),
                            Grade = 5,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 8
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2025, 8, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7434),
                            Grade = 4,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = 3
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2025, 11, 22, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7438),
                            Grade = 5,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 6
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2025, 9, 25, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7442),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 5
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2025, 9, 19, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7446),
                            Grade = 3,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = 9
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2025, 10, 15, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7449),
                            Grade = 5,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 7
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2025, 11, 17, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7453),
                            Grade = 3,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 4
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2025, 8, 27, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7457),
                            Grade = 2,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = 7
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2025, 10, 24, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7461),
                            Grade = 1,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = 6
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2025, 9, 28, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7465),
                            Grade = 3,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = 6
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2025, 11, 8, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7469),
                            Grade = 4,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 4
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2025, 11, 3, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7473),
                            Grade = 5,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 7
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2025, 11, 9, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7476),
                            Grade = 3,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 9
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2025, 10, 4, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7480),
                            Grade = 5,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2025, 10, 6, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7484),
                            Grade = 1,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 8
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2025, 9, 17, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7487),
                            Grade = 4,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = 7
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2025, 9, 24, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7590),
                            Grade = 3,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 9
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2025, 11, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7597),
                            Grade = 2,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 5
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2025, 10, 15, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7602),
                            Grade = 4,
                            ProductId = 7,
                            Rating = 2.1699999999999999,
                            ReviewCount = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2025, 8, 25, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7606),
                            Grade = 2,
                            ProductId = 2,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 7
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2025, 9, 6, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7610),
                            Grade = 4,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 8
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2025, 9, 19, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7613),
                            Grade = 4,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 4
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2025, 10, 17, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7618),
                            Grade = 4,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 6
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2025, 11, 10, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7623),
                            Grade = 3,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 4
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2025, 11, 23, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7627),
                            Grade = 4,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 8
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2025, 10, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7631),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consecte",
                            UserId = 1
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2025, 9, 17, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7635),
                            Grade = 2,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = 8
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2025, 9, 23, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7643),
                            Grade = 2,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = 3
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2025, 11, 12, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7648),
                            Grade = 3,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = 7
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2025, 9, 12, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7652),
                            Grade = 5,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 1
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2025, 10, 19, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7656),
                            Grade = 3,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipis",
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2025, 11, 25, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7660),
                            Grade = 4,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2025, 11, 23, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7664),
                            Grade = 3,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2025, 9, 3, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7668),
                            Grade = 1,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = 6
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2025, 10, 6, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7671),
                            Grade = 3,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = 1
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2025, 11, 3, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7676),
                            Grade = 4,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = 8
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2025, 10, 26, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7681),
                            Grade = 1,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consect",
                            UserId = 7
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2025, 11, 5, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7685),
                            Grade = 4,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2025, 9, 7, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7689),
                            Grade = 4,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 9
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2025, 11, 23, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7694),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 2
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2025, 10, 25, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7697),
                            Grade = 3,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = 1
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2025, 10, 12, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7702),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            UserId = 5
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2025, 9, 19, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7705),
                            Grade = 3,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut l",
                            UserId = 4
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2025, 8, 31, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7709),
                            Grade = 2,
                            ProductId = 7,
                            Rating = 2.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2025, 9, 29, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7715),
                            Grade = 1,
                            ProductId = 8,
                            Rating = 3.71,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = 4
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2025, 10, 18, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7718),
                            Grade = 2,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = 1
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2025, 9, 5, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7722),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2025, 9, 10, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7776),
                            Grade = 2,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 9
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2025, 11, 5, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7782),
                            Grade = 4,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 9
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2025, 9, 21, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7786),
                            Grade = 3,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 9
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2025, 9, 15, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7790),
                            Grade = 2,
                            ProductId = 3,
                            Rating = 3.75,
                            ReviewCount = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2025, 11, 4, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7795),
                            Grade = 5,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2025, 10, 24, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7799),
                            Grade = 5,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = 6
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2025, 9, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(7804),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 5
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2025, 11, 13, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8054),
                            Grade = 1,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 4
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2025, 9, 3, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8059),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2025, 11, 30, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8063),
                            Grade = 2,
                            ProductId = 6,
                            Rating = 3.1000000000000001,
                            ReviewCount = 10,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2025, 10, 8, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8067),
                            Grade = 3,
                            ProductId = 9,
                            Rating = 3.2200000000000002,
                            ReviewCount = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 7
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2025, 11, 2, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8071),
                            Grade = 5,
                            ProductId = 4,
                            Rating = 3.4300000000000002,
                            ReviewCount = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = 3
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2025, 11, 12, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8075),
                            Grade = 5,
                            ProductId = 1,
                            Rating = 4.1699999999999999,
                            ReviewCount = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2025, 11, 24, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8078),
                            Grade = 2,
                            ProductId = 7,
                            Rating = 2.1699999999999999,
                            ReviewCount = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2025, 11, 15, 21, 51, 21, 332, DateTimeKind.Local).AddTicks(8082),
                            Grade = 4,
                            ProductId = 5,
                            Rating = 2.9199999999999999,
                            ReviewCount = 12,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consect",
                            UserId = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
