// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Domain;

#nullable disable

namespace Review.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Review.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 10, 17, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1300),
                            Grade = 2.1400000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 9, 1, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1360),
                            Grade = 1.71,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 10, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1413),
                            Grade = 3.0,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 10, 3, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1632),
                            Grade = 2.6699999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 9, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1658),
                            Grade = 2.5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 9, 26, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1709),
                            Grade = 2.6699999999999999,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 8, 30, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1737),
                            Grade = 2.75,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 11, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1749),
                            Grade = 1.0,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 9, 16, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1776),
                            Grade = 2.75,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2025, 9, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1809),
                            Grade = 3.7999999999999998,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2025, 11, 12, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1908),
                            Grade = 1.5,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2025, 8, 25, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1964),
                            Grade = 2.8900000000000001,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2008),
                            Grade = 2.5699999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2025, 11, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2035),
                            Grade = 0.67000000000000004,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2059),
                            Grade = 0.67000000000000004,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2025, 9, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2200),
                            Grade = 2.6699999999999999,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2025, 9, 25, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2240),
                            Grade = 2.5,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2025, 10, 26, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2263),
                            Grade = 4.3300000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2025, 11, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2300),
                            Grade = 2.8300000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2025, 10, 17, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2353),
                            Grade = 1.8799999999999999,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2366),
                            Grade = 0.0,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2025, 10, 18, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2447),
                            Grade = 3.0,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2025, 11, 30, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2480),
                            Grade = 2.25,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2025, 11, 23, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2522),
                            Grade = 2.1699999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2025, 10, 26, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2565),
                            Grade = 2.5699999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2025, 11, 22, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2591),
                            Grade = 3.0,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2025, 9, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2608),
                            Grade = 1.5,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2025, 9, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2718),
                            Grade = 3.5,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2025, 11, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2738),
                            Grade = 3.0,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2025, 9, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2777),
                            Grade = 2.0,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2025, 10, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2814),
                            Grade = 3.1699999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2025, 10, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2851),
                            Grade = 2.7999999999999998,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2025, 11, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(2958),
                            Grade = 1.5700000000000001,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2025, 9, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3014),
                            Grade = 2.3300000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2025, 9, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3031),
                            Grade = 3.0,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2025, 9, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3087),
                            Grade = 1.8899999999999999,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2025, 9, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3126),
                            Grade = 1.4299999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2025, 9, 26, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3228),
                            Grade = 2.0,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2025, 9, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3275),
                            Grade = 2.3799999999999999,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2025, 9, 25, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3316),
                            Grade = 3.1699999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2025, 9, 11, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3342),
                            Grade = 3.5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2025, 9, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3455),
                            Grade = 2.5,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2025, 10, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3469),
                            Grade = 2.0,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2025, 10, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3497),
                            Grade = 3.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2025, 10, 11, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3525),
                            Grade = 2.5,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2025, 9, 17, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3562),
                            Grade = 3.0,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2025, 10, 18, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3600),
                            Grade = 2.0,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2025, 10, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3753),
                            Grade = 2.8300000000000001,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2025, 11, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3806),
                            Grade = 3.3300000000000001,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2025, 11, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3850),
                            Grade = 2.0,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3887),
                            Grade = 0.67000000000000004,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2025, 9, 2, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3899),
                            Grade = 2.0,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2025, 11, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(3993),
                            Grade = 3.0,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2025, 10, 6, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4021),
                            Grade = 2.6699999999999999,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2025, 11, 10, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4052),
                            Grade = 0.59999999999999998,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2025, 11, 22, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4096),
                            Grade = 1.4299999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2025, 10, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4137),
                            Grade = 2.4300000000000002,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2025, 9, 16, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4238),
                            Grade = 1.8600000000000001,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2025, 10, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4286),
                            Grade = 2.8599999999999999,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2025, 10, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4312),
                            Grade = 3.25,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2025, 11, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4351),
                            Grade = 3.1699999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2025, 10, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4391),
                            Grade = 3.5699999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4479),
                            Grade = 3.0,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2025, 11, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4498),
                            Grade = 2.5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2025, 11, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4523),
                            Grade = 1.5,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2025, 8, 27, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4536),
                            Grade = 5.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2025, 11, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4567),
                            Grade = 2.75,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2025, 10, 11, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4579),
                            Grade = 3.0,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2025, 10, 25, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4629),
                            Grade = 3.0,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2025, 10, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4719),
                            Grade = 2.0,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2025, 9, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4738),
                            Grade = 1.5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2025, 10, 2, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4769),
                            Grade = 4.2000000000000002,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2025, 8, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4798),
                            Grade = 4.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2025, 9, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4840),
                            Grade = 2.8599999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2025, 8, 31, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4889),
                            Grade = 2.5,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2025, 9, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(4990),
                            Grade = 3.8799999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5004),
                            Grade = 4.0,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2025, 11, 10, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5048),
                            Grade = 2.5699999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2025, 10, 12, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5066),
                            Grade = 2.0,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2025, 11, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5103),
                            Grade = 3.8300000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2025, 9, 1, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5183),
                            Grade = 2.6000000000000001,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2025, 8, 26, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5210),
                            Grade = 2.0,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2025, 10, 30, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5222),
                            Grade = 4.0,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2025, 10, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5239),
                            Grade = 2.0,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2025, 8, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5253),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2025, 9, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5314),
                            Grade = 1.8899999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2025, 9, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5359),
                            Grade = 2.0,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2025, 9, 6, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5456),
                            Grade = 2.3799999999999999,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2025, 11, 27, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5475),
                            Grade = 2.5,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5502),
                            Grade = 1.5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2025, 9, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5542),
                            Grade = 2.5699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2025, 8, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5577),
                            Grade = 2.3999999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2025, 11, 1, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5717),
                            Grade = 2.8799999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2025, 9, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5773),
                            Grade = 2.8900000000000001,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2025, 10, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5817),
                            Grade = 3.0,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2025, 9, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5866),
                            Grade = 2.2200000000000002,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2025, 9, 12, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5879),
                            Grade = 1.0,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2025, 10, 23, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5950),
                            Grade = 2.5,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2025, 9, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(5999),
                            Grade = 2.6200000000000001,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2025, 10, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(6049),
                            Grade = 1.1100000000000001,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 10, 27, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(342),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusm",
                            UserId = 9
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 9, 5, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(393),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, con",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 11, 21, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(401),
                            Grade = 3,
                            ProductId = 9,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 11, 11, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(405),
                            Grade = 1,
                            ProductId = 5,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 9, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(412),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 11, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(416),
                            Grade = 1,
                            ProductId = 4,
                            RatingId = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 11, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(420),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididun",
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 8, 30, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(565),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 9, 10, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(572),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(576),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2025, 10, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(580),
                            Grade = 2,
                            ProductId = 8,
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(585),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 8
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2025, 10, 11, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(590),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 2,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2025, 10, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(594),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusm",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2025, 9, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(599),
                            Grade = 4,
                            ProductId = 5,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2025, 10, 17, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(604),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2025, 11, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(608),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2025, 9, 30, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(614),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2025, 11, 3, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(619),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut l",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2025, 11, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(624),
                            Grade = 0,
                            ProductId = 4,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 5
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2025, 10, 11, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(628),
                            Grade = 0,
                            ProductId = 6,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2025, 9, 10, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(633),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 6
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2025, 10, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(637),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2025, 10, 3, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(641),
                            Grade = 3,
                            ProductId = 3,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2025, 11, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(645),
                            Grade = 4,
                            ProductId = 5,
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2025, 9, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(650),
                            Grade = 5,
                            ProductId = 7,
                            RatingId = 1,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = 6
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2025, 9, 5, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(655),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2025, 10, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(660),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, co",
                            UserId = 7
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2025, 11, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(664),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor si",
                            UserId = 5
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2025, 11, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(669),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = 5
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2025, 10, 31, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(673),
                            Grade = 0,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2025, 9, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(680),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = 6
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2025, 9, 10, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(685),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 9
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2025, 10, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(690),
                            Grade = 1,
                            ProductId = 4,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = 7
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2025, 10, 2, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(695),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 4,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2025, 9, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(699),
                            Grade = 3,
                            ProductId = 9,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2025, 9, 12, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(703),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 4
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2025, 10, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(707),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 8
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2025, 9, 22, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(715),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 5
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2025, 10, 10, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(721),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 6
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2025, 9, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(724),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 6
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2025, 11, 1, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(784),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 4
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2025, 9, 12, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(791),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2025, 10, 23, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(794),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusm",
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2025, 8, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(799),
                            Grade = 4,
                            ProductId = 5,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 3
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2025, 8, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(803),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 9
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(808),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 1
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2025, 10, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(813),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 7,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2025, 10, 27, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(818),
                            Grade = 4,
                            ProductId = 6,
                            RatingId = 1,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 5
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2025, 9, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(822),
                            Grade = 0,
                            ProductId = 6,
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, co",
                            UserId = 6
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2025, 10, 18, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(828),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 9
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2025, 10, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(832),
                            Grade = 4,
                            ProductId = 1,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 5
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2025, 11, 18, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(838),
                            Grade = 5,
                            ProductId = 3,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = 5
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2025, 8, 25, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(842),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2025, 11, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(846),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 2
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2025, 11, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(851),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 4
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2025, 9, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(855),
                            Grade = 4,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 3
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2025, 9, 20, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(859),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 9
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2025, 10, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(863),
                            Grade = 1,
                            ProductId = 3,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 7
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2025, 9, 9, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(868),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = 7
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2025, 11, 22, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(872),
                            Grade = 5,
                            ProductId = 7,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor si",
                            UserId = 4
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2025, 11, 4, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(877),
                            Grade = 5,
                            ProductId = 1,
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = 3
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(883),
                            Grade = 0,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 5
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2025, 9, 27, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(888),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 9
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2025, 11, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(891),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = 5
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2025, 10, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(896),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2025, 11, 23, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(900),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 7
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2025, 9, 18, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(905),
                            Grade = 3,
                            ProductId = 9,
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consecte",
                            UserId = 9
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2025, 10, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(910),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 4
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2025, 10, 16, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(915),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 5
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2025, 10, 23, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(920),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 8
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2025, 9, 19, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(925),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = 2
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2025, 9, 18, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(930),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = 4
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2025, 10, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(934),
                            Grade = 2,
                            ProductId = 8,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 6
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(938),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2025, 11, 1, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1004),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 6,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = 1
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2025, 9, 22, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1010),
                            Grade = 0,
                            ProductId = 4,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 8
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2025, 9, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1015),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 3
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2025, 11, 3, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1019),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ame",
                            UserId = 2
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2025, 11, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1023),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = 9
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2025, 10, 3, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1028),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 1
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2025, 11, 5, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1034),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 5
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2025, 9, 8, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1042),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 4,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = 1
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2025, 9, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1050),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 3,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 1
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2025, 8, 29, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1056),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 5
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2025, 9, 12, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1062),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2025, 10, 14, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1067),
                            Grade = 1,
                            ProductId = 1,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 5
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1071),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 5,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 5
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2025, 10, 22, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1076),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2025, 11, 15, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1086),
                            Grade = 0,
                            ProductId = 5,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = 5
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2025, 10, 23, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1090),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = 7
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2025, 8, 31, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1095),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 7
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2025, 8, 24, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1099),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 8,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = 8
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2025, 9, 26, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1103),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = 7
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2025, 10, 28, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1108),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consect",
                            UserId = 1
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2025, 9, 13, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1111),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 4,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 7
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2025, 9, 17, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1115),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 6
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2025, 10, 27, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1120),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 9,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = 6
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2025, 10, 7, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1124),
                            Grade = 3,
                            ProductId = 1,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = 8
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2025, 9, 2, 17, 25, 27, 950, DateTimeKind.Local).AddTicks(1130),
                            Grade = 2,
                            ProductId = 1,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut l",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.HasOne("Review.Domain.Models.Rating", "Rating")
                        .WithMany("Reviews")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Review.Domain.Models.Rating", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
